spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mom:db;Mode=MySql

---

spring:
  profiles: test

spring:
  datasource:
    driverCLassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/sampledev
    username: sample
    password: sample

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update

---    

spring:
  profiles: integration-test

spring:
  datasource:
    driverCLassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/sampledev
    username: sample
    password: sample

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update

---    

spring:
  profiles: uat

spring:
  datasource:
    driverCLassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/sampledev
    username: sample
    password: sample

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update
    
---

spring:
  profiles: prod

spring:
  datasource:
    driverCLassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/sampledev
    username: sample
    password: sample

spring.jpa:
  hibernate:
    dialect: org.hibernate.dialect.MySQLInnoDBDialect
    ddl-auto: update